# Mono/.NET are not officially supported. The following is a workaround.
language: c

before_install:
  - sudo bash -c "echo deb http://badgerports.org precise main >> /etc/apt/sources.list"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E1FAD0C
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-devel

install:
  - mozroots --import --sync --quiet

# Run the build script
script:
 - mono  ./.nuget/NuGet.exe install ./.nuget/packages.config -OutputDirectory packages
 - mono  ./.nuget/NuGet.exe restore ./NEventSocket.sln
 - xbuild ./NEventSocket.sln /property:Configuration=Release /nologo /verbosity:minimal
 - mono  ./packages/xunit.runners.1.9.2/tools/xunit.console.clr4.x86.exe ./test/NEventSocket.Tests/bin/Release/NEventSocket.Tests.dll

# Only watch the master branch.
branches:
 only:
   - master
   - develop
